# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bus_booking_pb2 as bus__booking__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bus_booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BusBookingServiceStub(object):
    """Bus Booking Service - gRPC API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCities = channel.unary_unary(
                '/bus_booking.BusBookingService/GetCities',
                request_serializer=bus__booking__pb2.Empty.SerializeToString,
                response_deserializer=bus__booking__pb2.CitiesResponse.FromString,
                _registered_method=True)
        self.SearchRoutes = channel.unary_unary(
                '/bus_booking.BusBookingService/SearchRoutes',
                request_serializer=bus__booking__pb2.SearchRoutesRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.RoutesResponse.FromString,
                _registered_method=True)
        self.GetDates = channel.unary_unary(
                '/bus_booking.BusBookingService/GetDates',
                request_serializer=bus__booking__pb2.GetDatesRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.DatesResponse.FromString,
                _registered_method=True)
        self.SearchTrips = channel.unary_unary(
                '/bus_booking.BusBookingService/SearchTrips',
                request_serializer=bus__booking__pb2.SearchTripsRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.TripsResponse.FromString,
                _registered_method=True)
        self.GetSeats = channel.unary_unary(
                '/bus_booking.BusBookingService/GetSeats',
                request_serializer=bus__booking__pb2.GetSeatsRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.SeatsResponse.FromString,
                _registered_method=True)
        self.SelectSeat = channel.unary_unary(
                '/bus_booking.BusBookingService/SelectSeat',
                request_serializer=bus__booking__pb2.SelectSeatRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.SelectSeatResponse.FromString,
                _registered_method=True)
        self.UnselectSeat = channel.unary_unary(
                '/bus_booking.BusBookingService/UnselectSeat',
                request_serializer=bus__booking__pb2.UnselectSeatRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.SelectSeatResponse.FromString,
                _registered_method=True)
        self.BookSeats = channel.unary_unary(
                '/bus_booking.BusBookingService/BookSeats',
                request_serializer=bus__booking__pb2.BookSeatsRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.BookSeatsResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.unary_unary(
                '/bus_booking.BusBookingService/UploadFile',
                request_serializer=bus__booking__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.StreamSeatUpdates = channel.unary_stream(
                '/bus_booking.BusBookingService/StreamSeatUpdates',
                request_serializer=bus__booking__pb2.StreamRequest.SerializeToString,
                response_deserializer=bus__booking__pb2.SeatUpdate.FromString,
                _registered_method=True)


class BusBookingServiceServicer(object):
    """Bus Booking Service - gRPC API
    """

    def GetCities(self, request, context):
        """Lấy danh sách thành phố
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRoutes(self, request, context):
        """Tìm kiếm tuyến đường
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDates(self, request, context):
        """Lấy ngày có chuyến
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTrips(self, request, context):
        """Tìm kiếm chuyến xe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeats(self, request, context):
        """Lấy trạng thái ghế
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectSeat(self, request, context):
        """Chọn ghế
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnselectSeat(self, request, context):
        """Bỏ chọn ghế
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookSeats(self, request, context):
        """Đặt vé
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request, context):
        """Upload file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSeatUpdates(self, request, context):
        """Stream realtime seat updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusBookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCities,
                    request_deserializer=bus__booking__pb2.Empty.FromString,
                    response_serializer=bus__booking__pb2.CitiesResponse.SerializeToString,
            ),
            'SearchRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRoutes,
                    request_deserializer=bus__booking__pb2.SearchRoutesRequest.FromString,
                    response_serializer=bus__booking__pb2.RoutesResponse.SerializeToString,
            ),
            'GetDates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDates,
                    request_deserializer=bus__booking__pb2.GetDatesRequest.FromString,
                    response_serializer=bus__booking__pb2.DatesResponse.SerializeToString,
            ),
            'SearchTrips': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTrips,
                    request_deserializer=bus__booking__pb2.SearchTripsRequest.FromString,
                    response_serializer=bus__booking__pb2.TripsResponse.SerializeToString,
            ),
            'GetSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeats,
                    request_deserializer=bus__booking__pb2.GetSeatsRequest.FromString,
                    response_serializer=bus__booking__pb2.SeatsResponse.SerializeToString,
            ),
            'SelectSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectSeat,
                    request_deserializer=bus__booking__pb2.SelectSeatRequest.FromString,
                    response_serializer=bus__booking__pb2.SelectSeatResponse.SerializeToString,
            ),
            'UnselectSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.UnselectSeat,
                    request_deserializer=bus__booking__pb2.UnselectSeatRequest.FromString,
                    response_serializer=bus__booking__pb2.SelectSeatResponse.SerializeToString,
            ),
            'BookSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.BookSeats,
                    request_deserializer=bus__booking__pb2.BookSeatsRequest.FromString,
                    response_serializer=bus__booking__pb2.BookSeatsResponse.SerializeToString,
            ),
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=bus__booking__pb2.UploadFileRequest.FromString,
                    response_serializer=bus__booking__pb2.UploadFileResponse.SerializeToString,
            ),
            'StreamSeatUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSeatUpdates,
                    request_deserializer=bus__booking__pb2.StreamRequest.FromString,
                    response_serializer=bus__booking__pb2.SeatUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bus_booking.BusBookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bus_booking.BusBookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BusBookingService(object):
    """Bus Booking Service - gRPC API
    """

    @staticmethod
    def GetCities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/GetCities',
            bus__booking__pb2.Empty.SerializeToString,
            bus__booking__pb2.CitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/SearchRoutes',
            bus__booking__pb2.SearchRoutesRequest.SerializeToString,
            bus__booking__pb2.RoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/GetDates',
            bus__booking__pb2.GetDatesRequest.SerializeToString,
            bus__booking__pb2.DatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTrips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/SearchTrips',
            bus__booking__pb2.SearchTripsRequest.SerializeToString,
            bus__booking__pb2.TripsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/GetSeats',
            bus__booking__pb2.GetSeatsRequest.SerializeToString,
            bus__booking__pb2.SeatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/SelectSeat',
            bus__booking__pb2.SelectSeatRequest.SerializeToString,
            bus__booking__pb2.SelectSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnselectSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/UnselectSeat',
            bus__booking__pb2.UnselectSeatRequest.SerializeToString,
            bus__booking__pb2.SelectSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/BookSeats',
            bus__booking__pb2.BookSeatsRequest.SerializeToString,
            bus__booking__pb2.BookSeatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bus_booking.BusBookingService/UploadFile',
            bus__booking__pb2.UploadFileRequest.SerializeToString,
            bus__booking__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSeatUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bus_booking.BusBookingService/StreamSeatUpdates',
            bus__booking__pb2.StreamRequest.SerializeToString,
            bus__booking__pb2.SeatUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
